### ISSUE TITLE
Keep back-end and front-end code in separate repositories

### ISSUE THREAD

**Issue by silvuss** [CoyoteNET/Coyote.NETCore#13]
### Problem

This issue is about to be a discussion on whether it would be OK to keep our project's code in two separate repositories: one for the front-end code, and one for the back-end code.

Three reasons that stay behind this idea were introduced by somekind in [this comment](https://github.com/dotNETSanta/Coyote.NETCore/issues/2#issuecomment-476912352) and are as follows:
> I think it's a bit strange to have back-end and front-end in one repository.
> 1. There will be single list of issues and branches. We will have to introduce some conventions to distinct these.
> 2. Continuous Integration will be painful or at least hard to configure. We will have to filter out front-end and back-end commits and run them in a different pipelines.
> 3. It have chance to work probably only if we use same technology at both ends. Is it possible? If not, then the name of repository will be very confusing.

_Originally posted by @smknd in https://github.com/dotNETSanta/Coyote.NETCore/issues/2#issuecomment-476912352_

Moreover, there are another reasons introduced in [this 2016 article](https://quickleft.com/blog/six-reasons-we-split-front-end-and-back-end-code-into-two-git-repositories-working-with-github-repositories/) by Simone Johnson. According to her, two separate repositories involves in particular (my summary):
1. not disrupting code that's already in place;
2. developers working synchronously on the front-end and back-end components of a feature;
3. making isolated deployments of the different code;
4. code staying cleaner and being easier to work with in the long-run.
5. having one person working on one feature, while another working on another one (including they agreed a communication between the software parts they create);
6. easier work scheduling – as developers in distinct repositories don't need to worry about each other's changes (too much ;) ).

When it comes to the opposite case (one repository), I will search for some reasons later (if the issue will still be open).

When it comes about transferring existing labels, issues, milestones and projects (that are created for both front-end and back-end features) to the new repository, I think there could be problems if there would be too much content (specifically – mixed together). The only easy way of transferring content from one repository to another that I know of is to transfer the whole issues (by clicking the button "Transfer issue"). I do not know any way to transfer labels, projects and milestones between repositories (apart from copy/paste). Moreover, issues are commented usually by different users, so to mirror the whole issue, each user would need to create their comment de novo (in the appropriate order).

Let's hope this discussion will not last too long, and we will decide on some solution before too much content (related to both front-end and back-end) is created. :) Personally, I think that no new content should be created before we close this issue.

### Current behaviour

Both the back-end code and the front-end code are kept in this repository.

### Expected behaviour

The back-end code is kept in this repository, and the front-end code is kept in another one.

**Comment by dotNETSanta** [comment]
Backend: https://github.com/dotNETSanta/Coyote.NETCore

Frontend: https://github.com/dotNETSanta/CoyoteFrontend
